[book]
authors = ["adisbladis"]
language = "en"
multilingual = false
src = "src"
title = "Pyproject.nix"

[preprocessor.nixdoc]
command = "mdbook-nixdoc"

[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"
renderer = ["html"]

[output.html]
git-repository-url = "https://github.com/nix-community/pyproject.nix"
git-branch = "master"
open-on-text = "Found an issue? [Edit this page on GitHub.]"
