name: Github Pages

on:
  push:
    branches:
      - master

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.1
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v4
    - name: Run Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@v1
    - name: Run build
      run: nix build -L .#doc-html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./result
        force_orphan: true
